#!/bin/bash
# vboxmanage list vms
#vboxmanage list runningvms
#-----
runvm() {
	if [[ $2 -eq 0 ]]; then get=gui; else get=headless; fi
	vboxmanage startvm "$1" --type $get
}
stopvm() {
	if [[ $2 -eq 0 ]]; then get=gui; else get=headless; fi	
	vboxmanage controlvm "$1" poweroff --type $get
}
listvm() {
	name=$(vboxmanage list vms | cut -d '"' -f 2)
	name_run=$(vboxmanage list runningvms | cut -d '"' -f 2 | tr -s '\n' ' ')
	uid=$(vboxmanage list vms | cut -d '"' -f 3 | tr -d ' ')
	tot_avail=$(vboxmanage list vms | cut -d '"' -f 2 | wc -l)
	tot_run=$(vboxmanage list runningvms | cut -d '"' -f 2 | wc -l)

	echo -e "NAME UID IP\n----- ----- -----" > /tmp/vbox.fetch
	vboxmanage list vms > /tmp/listvm
	paste /tmp/listvm syn9.ip > /tmp/fullvm
	cat /tmp/fullvm >> /tmp/vbox.fetch
	cat /tmp/vbox.fetch | tr -d '"{}' | tr -s '\t' ' '  |column -s ' ' -t

	echo -e "-----\n[$tot_run/$tot_avail] ON:   $name_run..."
}
#-----
type=0
while getopts ":r:s: :l :g :h" opt; do
        case $opt in
                r) r="${OPTARG}" ;;
                s) s="${OPTARG}" ;;
		g) type=0 ;;
		h) type=1 ;;
		l) listvm ;;
        esac
done
#-----
if [[ "$r" && "$type" ]]; then runvm "$r" "$type" ; exit 0; fi
if [[ "$s" && "$type" ]]; then stopvm "$s" "$type" ; exit 0; fi
exit 0
